---
version: '2.1'
services:
  dev:
    build: .
    image: greenwave_dev
    user: ${DEV_USER_ID:-1000}
    working_dir: /src
    env_file: ["docker/dev.env"]
    command: ["bash", "-c", "./docker/dev-command.sh"]
    volumes:
      - ./:/src:ro,z
      - ./docker/home:/home/dev:rw,z
      - ./docker/greenwave-settings.py:/etc/greenwave/settings.py:ro,z
      - ./conf/policies/:/etc/greenwave/policies/:ro,z
      - ./conf/subject_types/:/etc/greenwave/subject_types/:ro,z
    ports:
      - 8080:8080
    depends_on:
      - memcached
      - resultsdb
      - waiverdb

  resultsdb-db:
    image: postgres:9.5.2
    restart: always
    env_file: ["docker/resultsdb-db.env"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 30s
      retries: 3

  resultsdb:
    build:
      context: ../resultsdb
      dockerfile: Dockerfile
    working_dir: /code
    environment:
      - GREENWAVE_LISTENERS=${GREENWAVE_LISTENERS:-1}
    command: ["bash", "-c", "/start.sh"]
    volumes:
      - ../resultsdb:/code:ro,z
      - ./docker/home:/home/dev:rw,z
      - ./docker/resultsdb-command.sh:/start.sh:ro,z
      - ./docker/resultsdb-settings.py:/etc/resultsdb/settings.py:ro,z
      - ./docker/resultsdb.conf:/etc/httpd/conf.d/resultsdb.conf:ro,z
    ports:
      - 5001:5001
    depends_on:
      resultsdb-db:
        condition: service_healthy

  waiverdb-db:
    image: postgres:9.5.2
    restart: always
    env_file: ["docker/waiverdb-db.env"]

  waiverdb:
    build:
      context: ../waiverdb
      dockerfile: openshift/containers/waiverdb/Dockerfile
    working_dir: /code
    env_file: ["docker/waiverdb.env"]
    environment:
      - GREENWAVE_LISTENERS=${GREENWAVE_LISTENERS:-1}
    command: ["bash", "-c", "/start.sh"]
    volumes:
      - ../waiverdb:/code:ro,z
      - ./docker/home:/home/dev:rw,z
      - ./docker/waiverdb-command.sh:/start.sh:ro,z
      - ./docker/waiverdb-settings.py:/etc/waiverdb/settings.py:ro,z
      - ./docker/client_secrets.json:/etc/secret/client_secrets.json:ro,z
    ports:
      - 5004:5004
    user: '0'
    depends_on:
      - waiverdb-db

  memcached:
    image: "quay.io/factory2/memcached"

  resultsdb-listener:
    build: .
    image: greenwave_dev
    user: ${DEV_USER_ID:-1000}
    working_dir: /
    env_file: ["docker/dev.env"]
    command:
      - "gunicorn"
      - "--reload"
      - "--workers=2"
      - "--threads=2"
      - "--bind=0.0.0.0:8082"
      - "--access-logfile=-"
      - "--enable-stdio-inheritance"
      - "greenwave.resultsdb_listener:app"
    ports:
      - 8082:8082
    volumes:
      - ./:/src:ro,z
      - ./docker/home:/home/dev:rw,z
      - ./docker/greenwave-settings.py:/etc/greenwave/settings.py:ro,z
      - ./conf/policies/:/etc/greenwave/policies/:ro,z
      - ./conf/subject_types/:/etc/greenwave/subject_types/:ro,z
    depends_on:
      - memcached
      - umb
    deploy:
      replicas: ${GREENWAVE_LISTENERS:-1}

  waiverdb-listener:
    build: .
    image: greenwave_dev
    user: ${DEV_USER_ID:-1000}
    working_dir: /
    env_file: ["docker/dev.env"]
    command:
      - "gunicorn"
      - "--reload"
      - "--workers=2"
      - "--threads=2"
      - "--bind=0.0.0.0:8083"
      - "--access-logfile=-"
      - "--enable-stdio-inheritance"
      - "greenwave.waiverdb_listener:app"
    ports:
      - 8083:8083
    volumes:
      - ./:/src:ro,z
      - ./docker/home:/home/dev:rw,z
      - ./docker/greenwave-settings.py:/etc/greenwave/settings.py:ro,z
      - ./conf/policies/:/etc/greenwave/policies/:ro,z
      - ./conf/subject_types/:/etc/greenwave/subject_types/:ro,z
    depends_on:
      - memcached
      - umb
    deploy:
      replicas: ${GREENWAVE_LISTENERS:-1}

  umb:
    image: images.paas.redhat.com/exd-sp-guild-c3i/umb:latest
    restart: unless-stopped
    command:
      - "java"
      - "-jar"
      - "/usr/share/umb/umb.jar"
      - "--spring.config.location=/etc/umb.yml"
    volumes:
      - ./docker/umb.yml:/etc/umb.yml:ro,z
    ports:
      - 5671:5671    # amqp
      - 61612:61612  # stomp
    deploy:
      replicas: ${GREENWAVE_LISTENERS:-1}

networks:
  default:
    driver: bridge
